// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAJ1YXLgyJLDauqEHfQSCP_Xjcw2AIyE',
    appId: '1:860589620350:web:4acd7c2ded3e7cd3dfac2f',
    messagingSenderId: '860589620350',
    projectId: 'email-generator-5305c',
    authDomain: 'email-generator-5305c.firebaseapp.com',
    storageBucket: 'email-generator-5305c.appspot.com',
    measurementId: 'G-RYV0HBQCVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSoq6r0-2EeeFr_ECxjvwobNzb1-wLHk',
    appId: '1:860589620350:android:a1464615ef1ad354dfac2f',
    messagingSenderId: '860589620350',
    projectId: 'email-generator-5305c',
    storageBucket: 'email-generator-5305c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxAjmzwGqgXLHFwP7ewb7ro6Q05hhXGQ',
    appId: '1:860589620350:ios:d9775586ee6e9d7ddfac2f',
    messagingSenderId: '860589620350',
    projectId: 'email-generator-5305c',
    storageBucket: 'email-generator-5305c.appspot.com',
    androidClientId:
        '860589620350-921vna720nnkl673argrnmps8plrtep5.apps.googleusercontent.com',
    iosClientId:
        '860589620350-k3elqtmpmo5vf2fv7ag3d6cg8h7pfil1.apps.googleusercontent.com',
    iosBundleId: 'com.wilfredalmeida.emailgenerator',
  );
}
